02-02-2019/Studentdetails/Studentdetails/Models/Studentdept.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Studentdetails.Models
{
    public class Studentdept
    {
        public int StudentdeptId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name ="Enter Department Name")]
        public string Deptname { get; set; }
    }
}

02-02-2019/Studentdetails/Studentdetails/Controllers/StudentdeptsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Studentdetails.Models;

namespace Studentdetails.Controllers
{
    public class StudentdeptsController : Controller
    {
        private Studentcontext db = new Studentcontext();

        // GET: Studentdepts
        public ActionResult Index()
        {
            return View(db.Studentdepts.ToList());
        }

        // GET: Studentdepts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studentdept studentdept = db.Studentdepts.Find(id);
            if (studentdept == null)
            {
                return HttpNotFound();
            }
            return View(studentdept);
        }

        // GET: Studentdepts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Studentdepts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentdeptId,Deptname")] Studentdept studentdept)
        {
            if (ModelState.IsValid)
            {
                db.Studentdepts.Add(studentdept);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentdept);
        }

        // GET: Studentdepts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studentdept studentdept = db.Studentdepts.Find(id);
            if (studentdept == null)
            {
                return HttpNotFound();
            }
            return View(studentdept);
        }

        // POST: Studentdepts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentdeptId,Deptname")] Studentdept studentdept)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentdept).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studentdept);
        }

        // GET: Studentdepts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studentdept studentdept = db.Studentdepts.Find(id);
            if (studentdept == null)
            {
                return HttpNotFound();
            }
            return View(studentdept);
        }

        // POST: Studentdepts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Studentdept studentdept = db.Studentdepts.Find(id);
            db.Studentdepts.Remove(studentdept);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

02-02-2019/Studentdetails/Studentdetails/Controllers/StudentinfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Studentdetails.Models;

namespace Studentdetails.Controllers
{
    public class StudentinfoesController : Controller
    {
        private Studentcontext db = new Studentcontext();

        // GET: Studentinfoes
        public ActionResult Index()
        {
            var studentinfoes = db.Studentinfoes.Include(s => s.Studentdept);
            return View(studentinfoes.ToList());
        }

        // GET: Studentinfoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studentinfo studentinfo = db.Studentinfoes.Find(id);
            if (studentinfo == null)
            {
                return HttpNotFound();
            }
            return View(studentinfo);
        }

        // GET: Studentinfoes/Create
        public ActionResult Create()
        {
            ViewBag.StudentdeptId = new SelectList(db.Studentdepts, "StudentdeptId", "Deptname");
            return View();
        }

        // POST: Studentinfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentinfoId,StudentdeptId,studsubject,studmark")] Studentinfo studentinfo)
        {
            if (ModelState.IsValid)
            {
                db.Studentinfoes.Add(studentinfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StudentdeptId = new SelectList(db.Studentdepts, "StudentdeptId", "Deptname", studentinfo.StudentdeptId);
            return View(studentinfo);
        }

        // GET: Studentinfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studentinfo studentinfo = db.Studentinfoes.Find(id);
            if (studentinfo == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentdeptId = new SelectList(db.Studentdepts, "StudentdeptId", "Deptname", studentinfo.StudentdeptId);
            return View(studentinfo);
        }

        // POST: Studentinfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentinfoId,StudentdeptId,studsubject,studmark")] Studentinfo studentinfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentinfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StudentdeptId = new SelectList(db.Studentdepts, "StudentdeptId", "Deptname", studentinfo.StudentdeptId);
            return View(studentinfo);
        }

        // GET: Studentinfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studentinfo studentinfo = db.Studentinfoes.Find(id);
            if (studentinfo == null)
            {
                return HttpNotFound();
            }
            return View(studentinfo);
        }

        // POST: Studentinfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Studentinfo studentinfo = db.Studentinfoes.Find(id);
            db.Studentinfoes.Remove(studentinfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

02-02-2019/Studentdetails/Studentdetails/Views/Studentdepts/Create.cshtml
@model Studentdetails.Models.Studentdept

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Studentdept</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Deptname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deptname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deptname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

02-02-2019/Studentdetails/Studentdetails/Views/Studentdepts/Delete.cshtml
@model Studentdetails.Models.Studentdept

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Studentdept</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Deptname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deptname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

02-02-2019/Studentdetails/Studentdetails/Views/Studentdepts/Details.cshtml
@model Studentdetails.Models.Studentdept

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Studentdept</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Deptname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deptname)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentdeptId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

02-02-2019/Studentdetails/Studentdetails/Views/Studentdepts/Edit.cshtml
@model Studentdetails.Models.Studentdept

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Studentdept</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentdeptId)

        <div class="form-group">
            @Html.LabelFor(model => model.Deptname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deptname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deptname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

02-02-2019/Studentdetails/Studentdetails/Views/Studentdepts/Index.cshtml
@model IEnumerable<Studentdetails.Models.Studentdept>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @Html.ActionLink("Add Subject", "index", "Studentinfoes")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Deptname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Deptname)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.StudentdeptId }) |
            @Html.ActionLink("Details", "Details", new { id=item.StudentdeptId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.StudentdeptId })
        </td>
    </tr>
}

</table>